apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/andrei-lupsa/dispatcher-service/k8s?ref=master

patches:
  - path: patch-env.yml

configMapGenerator:
  - behavior: merge
    files:
      - application-staging.yml
    name: dispatcher-config

images:
  - name: dispatcher-service
    newName: ghcr.io/andrei-lupsa/dispatcher-service
    newTag: latest

replicas:
  - name: dispatcher-service
    count: 1