name: polar-deployment
services:

  catalog-service:
    depends_on:
      - polar-postgres
      - config-service
    image: "ghcr.io/andrei-lupsa/catalog-service:0.0.1-SNAPSHOT"
    container_name: "catalog-service"
    ports:
      - "9001:9001"
#      - "8001:8001"
    environment:
      - BPL_JVM_THREAD_COUNT=50
#      - BPL_DEBUG_ENABLED=true
#      - BPL_DEBUG_PORT=8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog
      - SPRING_PROFILES_ACTIVE=testdata
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888

  order-service:
    depends_on:
      - polar-postgres
      - config-service
    image: "ghcr.io/andrei-lupsa/order-service:0.0.1-SNAPSHOT"
    container_name: "order-service"
    ports:
      - "9002:9002"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_R2DBC_URL=r2dbc:postgresql://polar-postgres:5432/polardb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://polar-postgres:5432/polardb_order
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - POLAR_CATALOG-SERVICE-URI=http://catalog-service:9001

  polar-postgres:
    image: "postgres:16.4"
    container_name: "polar-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  polar-redis:
    image: redis:7.4
    container_name: polar-redis
    ports:
      - "6379:6379"

  config-service:
    image: "ghcr.io/andrei-lupsa/config-service:0.0.1-SNAPSHOT"
    container_name: "config-service"
    ports:
      - "8888:8888"
    environment:
      - BPL_JVM_THREAD_COUNT=50

  polar-rabbitmq:
    image: rabbitmq:4.0-management
    container_name: polar-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf