name: polar-deployment
services:

  edge-service:
    depends_on:
      - config-service
      - polar-redis
      - catalog-service
      - order-service
    image: "ghcr.io/andrei-lupsa/edge-service:latest"
    container_name: "edge-service"
    ports:
      - "9000:9000"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_PROFILES_ACTIVE=k8s
      - CATALOG_SERVICE_URL=http://catalog-service:9001
      - ORDER_SERVICE_URL=http://order-service:9002
      - SPA_URL=http://polar-ui:9004
    restart: unless-stopped

  dispatcher-service:
    depends_on:
      - config-service
      - polar-rabbitmq
    image: "ghcr.io/andrei-lupsa/dispatcher-service:latest"
    container_name: "dispatcher-service"
    ports:
      - "9003:9003"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_PROFILES_ACTIVE=k8s
    restart: unless-stopped

  catalog-service:
    depends_on:
      - polar-postgres
      - config-service
    image: "ghcr.io/andrei-lupsa/catalog-service:latest"
    container_name: "catalog-service"
    ports:
      - "9001:9001"
#      - "8001:8001"
    environment:
      - BPL_JVM_THREAD_COUNT=50
#      - BPL_DEBUG_ENABLED=true
#      - BPL_DEBUG_PORT=8001
      - SPRING_PROFILES_ACTIVE=k8s,testdata
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
    restart: unless-stopped

  order-service:
    depends_on:
      - polar-postgres
      - config-service
      - polar-rabbitmq
    image: "ghcr.io/andrei-lupsa/order-service:latest"
    container_name: "order-service"
    ports:
      - "9002:9002"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_PROFILES_ACTIVE=k8s
      - POLAR_CATALOG_SERVICE_URI=http://catalog-service:9001
    restart: unless-stopped

  polar-postgres:
    image: "postgres:16.4"
    container_name: "polar-postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  polar-redis:
    image: redis:7.4
    container_name: polar-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  config-service:
    image: "ghcr.io/andrei-lupsa/config-service:latest"
    container_name: "config-service"
    ports:
      - "8888:8888"
    environment:
      - BPL_JVM_THREAD_COUNT=50
    restart: unless-stopped

  polar-rabbitmq:
    image: rabbitmq:4.0-management
    container_name: polar-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    restart: unless-stopped

  polar-keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: "polar-keycloak"
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - 8080:8080
    restart: unless-stopped

  polar-ui:
    image: "ghcr.io/polarbookshop/polar-ui:v1"
    container_name: "polar-ui"
    ports:
      - 9004:9004
    environment:
      - PORT=9004
    restart: unless-stopped