name: polar-deployment
services:

  config-service:
    depends_on:
      - fluent-bit
      - tempo
    image: "ghcr.io/andrei-lupsa/config-service:latest"
    pull_policy: always
    container_name: "config-service"
    ports:
      - "8888:8888"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - JAVA_TOOL_OPTIONS=-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-2.9.0.jar
      - OTEL_SERVICE_NAME=config-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
      - OTEL_METRICS_EXPORTER=none
    restart: unless-stopped
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224

  edge-service:
    depends_on:
      - fluent-bit
      - config-service
      - polar-keycloak
      - polar-redis
      - polar-ui
      - tempo
    image: "ghcr.io/andrei-lupsa/edge-service:latest"
    pull_policy: always
    container_name: "edge-service"
    ports:
      - "9000:9000"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - JAVA_TOOL_OPTIONS=-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-2.9.0.jar
      - OTEL_SERVICE_NAME=edge-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
      - OTEL_METRICS_EXPORTER=none
      - SPRING_CLOUD_CONFIG_ENABLED=true
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_PROFILES_ACTIVE=docker
      - CATALOG_SERVICE_URL=http://catalog-service:9001
      - ORDER_SERVICE_URL=http://order-service:9002
      - SPA_URL=http://polar-ui:9004
    restart: unless-stopped
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224

  dispatcher-service:
    depends_on:
      - fluent-bit
      - config-service
      - polar-rabbitmq
      - tempo
    image: "ghcr.io/andrei-lupsa/dispatcher-service:latest"
    pull_policy: always
    container_name: "dispatcher-service"
    ports:
      - "9003:9003"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - JAVA_TOOL_OPTIONS=-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-2.9.0.jar
      - OTEL_SERVICE_NAME=dispatcher-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
      - OTEL_METRICS_EXPORTER=none
      - SPRING_CLOUD_CONFIG_ENABLED=true
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224

  catalog-service:
    depends_on:
      - fluent-bit
      - polar-postgres
      - polar-keycloak
      - config-service
      - tempo
    image: "ghcr.io/andrei-lupsa/catalog-service:latest"
    pull_policy: always
    container_name: "catalog-service"
    ports:
      - "9001:9001"
#      - "8001:8001"
    environment:
      - BPL_JVM_THREAD_COUNT=50
#      - BPL_DEBUG_ENABLED=true
#      - BPL_DEBUG_PORT=8001
      - JAVA_TOOL_OPTIONS=-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-2.9.0.jar
      - OTEL_SERVICE_NAME=catalog-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
      - OTEL_METRICS_EXPORTER=none
      - SPRING_PROFILES_ACTIVE=docker,testdata
      - SPRING_CLOUD_CONFIG_ENABLED=true
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - THC_PATH=/actuator/health
      - THC_PORT=9001
    healthcheck:
      test: ["CMD", "/workspace/health-check"]
    restart: unless-stopped
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224

  order-service:
    depends_on:
      - fluent-bit
      - polar-postgres
      - config-service
      - polar-keycloak
      - polar-rabbitmq
      - tempo
    image: "ghcr.io/andrei-lupsa/order-service:latest"
    pull_policy: always
    container_name: "order-service"
    ports:
      - "9002:9002"
    environment:
      - BPL_JVM_THREAD_COUNT=50
      - JAVA_TOOL_OPTIONS=-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-2.9.0.jar
      - OTEL_SERVICE_NAME=order-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
      - OTEL_METRICS_EXPORTER=none
      - SPRING_CLOUD_CONFIG_ENABLED=true
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_PROFILES_ACTIVE=docker
      - POLAR_CATALOG_SERVICE_URI=http://catalog-service:9001
    restart: unless-stopped
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224

  polar-ui:
    image: "ghcr.io/polarbookshop/polar-ui:v1"
    container_name: "polar-ui"
    ports:
      - "9004:9004"
    environment:
      - PORT=9004
    restart: unless-stopped

  polar-postgres:
    image: "postgres:16.4"
    container_name: "polar-postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  polar-redis:
    image: redis:7.4
    container_name: polar-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  polar-rabbitmq:
    image: rabbitmq:4.0-management
    container_name: polar-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    restart: unless-stopped

  polar-keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: "polar-keycloak"
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - "8080:8080"
    restart: unless-stopped

  # Observability

  grafana:
    image: grafana/grafana-oss:11.3.0
    container_name: grafana
    depends_on:
      - loki
      - prometheus
      - tempo
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=password
    volumes:
      - ./observability/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./observability/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./observability/grafana/grafana.ini:/etc/grafana/grafana.ini

  loki:
    image: grafana/loki:3.2.1
    container_name: loki
    depends_on:
      - fluent-bit
    ports:
      - "3100:3100"

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:3.2.1
    container_name: fluent-bit
    ports:
      - "24224:24224"
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./observability/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

  prometheus:
    image: quay.io/prometheus/prometheus:v2.55.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  tempo:
    image: grafana/tempo:2.6.1
    container_name: tempo
    command: -config.file=/etc/tempo-config.yml
    ports:
      - "3110:3100" # Tempo
      - "4317:4317" # OTel
      - "4318:4318" # OTel
    volumes:
      - ./observability/tempo/tempo.yml:/etc/tempo-config.yml