# Deploy resources
k8s_yaml(['../../platform/development/services/postgresql.yml',
          '../../platform/development/services/rabbitmq.yml',
          '../../platform/development/services/redis.yml'])

include('../../../../config-service/Tiltfile')
include('../../../../edge-service/Tiltfile')
include('../../../../dispatcher-service/Tiltfile')
include('../../../../order-service/Tiltfile')
include('../../../../catalog-service/Tiltfile')

update_settings(max_parallel_updates=1)